force-app/main/default/objects/DocumentType__mdt/DocumentType__mdt.object-meta.xml
<CustomObject>
    <label>DocumentType</label>
    <pluralLabel>DocumentTypes</pluralLabel>
</CustomObject>

force-app/main/default/objects/DocumentType__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/UploadFilesByMetadataControllerTest.cls
@isTest
private class UploadFilesByMetadataControllerTest {
  @isTest
  static void testInternalView() {
    DocumentType__mdt record = UploadFilesByMetadataController.getViewDefinition(
      'LOB 1',
      'System Administrator',
      false
    );
    System.assertEquals(
      record.Type__c,
      'Category A;Category B;Category C;Category D;Category E;Category F; Category G; Category H; Category I; Category J; Category K;'
    );
  }

  @isTest
  static void testPartnerView() {
    DocumentType__mdt record = UploadFilesByMetadataController.getViewDefinition(
      'LOB 1',
      'Customer Community User',
      true
    );
    System.assertEquals(
      record.Type__c,
      'Category A;Category B;Category C;Category D;Category E'
    );
  }

  @isTest
  static void testInternalUpload() {
    DocumentType__mdt record = UploadFilesByMetadataController.getUploadDefinition(
      'LOB 1',
      'System Administrator',
      false
    );
    System.assertEquals(
      record.Type__c,
      'Category B;Category C;Category D;Category E;Category F; Category G; Category H; Category I; Category J; Category K;'
    );
  }

  @isTest
  static void testPartnerUpload() {
    DocumentType__mdt record = UploadFilesByMetadataController.getUploadDefinition(
      'LOB 1',
      'Customer Community User',
      true
    );
    System.assertEquals(record.Type__c, 'Category A;Category B;');
  }
}